### ISSUE TITLE
To DO

### ISSUE THREAD

**Issue by qingjian1991** [qingjian1991/MPTevol#2]
1. 写说明文档
2. 总结能够添加的新的功能

**Comment by ShixiangWang** [comment]
我列一下看到的一些问题，有的直接在代码注释里面写了 TODO。

1. 每个公开（export）的函数尽量造一个简单例子，这样方便测试。我目前只能关注描述和一些包引入（函数）的问题，一些具体的操作可能没有办法测试。
2. 目前网上找不到 `MEDICCquant` 这个包的下载地址。
3. `plotCNAprofile()`有一个`blank_genome1`函数，不知道其来源？`CNAqc`只能查到一个`blank_genome()`函数。
4. `readCNAProfile()`和`plotCNAProfile()`可以提供一个统一地例子，放到`readCNAprofile()`中。目前看到的vignette里面的数据不能复用该函数。
5. calKaKs 和 getKaKs 的区别是什么？
6. 一些函数参数的命名尽量保持一致，例如下面`.`, `_`以及骆驼法都出现了。

```
function(maf,
                        PrimaryId,
                        patient.id = NULL,
                        CCF_cutoff = 0.10,
                        pairByTumor = TRUE,
                        use.tumorSampleLabel = FALSE,
                        maf_drivers = NULL,
                        subtitle = "both",
                        ...
```

**Comment by ShixiangWang** [comment]
@qingjian1991 有空看下上面的问题哈

**Comment by ShixiangWang** [comment]
这里引入的`submod_13r_3w`找不到。

```
getKaKs <- function(df, vaf_cutoff = 0.05) {
  data(list = sprintf("submod_%s", "13r_3w"), package = "dndscv") # TODO not valid operation in package
```

**Comment by ShixiangWang** [comment]
抛开vignette不谈，包的check还存在不少问题，需要解决

```
devtools::check(vignettes = FALSE)
```

主要关注函数是否正常地完成了工作，解决check提示的error和warning（跟包本身无关的warning不算，例如`Warning: package ‘tidyr’ was built under R version 4.1.2`）

**Comment by qingjian1991** [comment]
> 这里引入的`submod_13r_3w`找不到。
> 
> ```
> getKaKs <- function(df, vaf_cutoff = 0.05) {
>   data(list = sprintf("submod_%s", "13r_3w"), package = "dndscv") # TODO not valid operation in package
> ```
这个已经修改完成

**Comment by qingjian1991** [comment]
已经解决了**MEDICCquant**的依赖问题，去除了**MEDICCquant**相关的函数。

**Comment by ShixiangWang** [comment]
OK

**Comment by qingjian1991** [comment]
> 这里引入的`submod_13r_3w`找不到。
> 
> ```
> getKaKs <- function(df, vaf_cutoff = 0.05) {
>   data(list = sprintf("submod_%s", "13r_3w"), package = "dndscv") # TODO not valid operation in package
> ```

这个问题已经解决

**Comment by qingjian1991** [comment]
> 我列一下看到的一些问题，有的直接在代码注释里面写了 TODO。
> 
> 1. 每个公开（export）的函数尽量造一个简单例子，这样方便测试。我目前只能关注描述和一些包引入（函数）的问题，一些具体的操作可能没有办法测试。
> 2. 目前网上找不到 `MEDICCquant` 这个包的下载地址。
> 3. `plotCNAprofile()`有一个`blank_genome1`函数，不知道其来源？`CNAqc`只能查到一个`blank_genome()`函数。
> 4. `readCNAProfile()`和`plotCNAProfile()`可以提供一个统一地例子，放到`readCNAprofile()`中。目前看到的vignette里面的数据不能复用该函数。
> 5. calKaKs 和 getKaKs 的区别是什么？
> 6. 一些函数参数的命名尽量保持一致，例如下面`.`, `_`以及骆驼法都出现了。
> 
> ```
> function(maf,
>                         PrimaryId,
>                         patient.id = NULL,
>                         CCF_cutoff = 0.10,
>                         pairByTumor = TRUE,
>                         use.tumorSampleLabel = FALSE,
>                         maf_drivers = NULL,
>                         subtitle = "both",
>                         ...
> ```

1.  这个包的依赖已经解决，目前不需要这个包了**MEDICCquant**
2. 第3和4个问题，目前相关的函数等待后续更新，现在只解决依赖问题。

**Comment by ShixiangWang** [comment]
@qingjian1991 这个包目前还有哪些问题要处理呢？
